---
# tasks file for jira

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: jira

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: jira

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: jira
