---
# tasks file for jira

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: jira

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: jira

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: jira

- name: Create JIRA working directory
  file: >
    path={{ jira_work_dir }}
    owner=root
    group=root
    mode=0755
    state=directory
  tags: jira

- name: Download JIRA
  get_url: >
    url={{ jira_download_url }}
    dest={{ jira_work_dir }}/{{ jira_binary }}
    sha256sum={{ jira_binary_sha256sum }}
  tags: jira

- name: Ensure the JIRA installation file is executable
  file: >
    path={{ jira_binary_path }}
    mode=0744
    state=touch
  tags: jira

- name: Create JIRA unattended response file
  template: >
    src=jira.response.varfile.j2
    dest={{ jira_response_path }}
  tags: jira

- name: Install JIRA in unattended mode
  command: "{{ jira_binary_path }} -q -varfile {{ jira_response_path }}"
  args:
    chdir: "{{ jira_work_dir }}/"
    creates: jira_installed
  tags: jira

- name: Create JIRA database
  mysql_db: >
    name={{ jira_database_name }}
    collation={{ jira_database_collation }}
    encoding={{ jira_database_encoding }}
    state=present
  tags: jira

- name: Create JIRA database user
  mysql_user: >
    name={{ jira_database_user }}
    password={{ jira_database_user_password }}
    priv={{ jira_database_user_priv }}
    state=present
  tags: jira

- name: Download MySQL Java connector
  get_url: >
    url={{ jira_mysql_connector_url }}
    dest={{ jira_work_dir }}/{{ jira_mysql_connector }}
    sha256sum={{ jira_mysql_connector_sha256sum }}
  tags: jira

- name: Unarchive MySQL Java connector
  unarchive: >
    src={{ jira_work_dir }}/{{ jira_mysql_connector }}
    dest={{ jira_work_dir }}/
    copy=no
  tags: jira

- name: Copy MySQL Java connector file
  command: cp {{ jira_work_dir }}/mysql-connector-java-5.1.34/mysql-connector-java-5.1.34-bin.jar {{ jira_install_dir }}/lib/
  args:
    creates: "{{ jira_install_dir }}/lib/mysql-connector-java-5.1.34-bin.jar"
  tags: jira

- name: Create JIRA database configuration file
  template: >
    src=dbconfig.xml.j2
    dest={{ jira_data_dir }}/dbconfig.xml
    owner=jira
    group=jira
    mode=0644
  notify: restart jira
  tags: jira

- name: Ensure JIRA service is started and enabled on boot
  service: name={{ jira_service_name }} state=started enabled=yes
  tags: jira
